version: '3.9'

networks:
  nginx-php8.2-postgres-node:

services:

  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.2-service
      - postgres-service
    networks:
      - nginx-php8.2-postgres-node

  #php
  php8.2-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php8.2-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php8.2-postgres-node
    depends_on:
      - postgres-service

  #postgres
  postgres-service:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  #node
  node-service:
      image: node:latest
      container_name: node-container
      volumes:
          - ./app:/var/www/project
      working_dir: /var/www/project
      networks:
          - nginx-php8.2-postgres-node